### ISSUE TITLE
No intermediate release strategy state transitions on new application abort

### ISSUE THREAD

**Issue by icanhazbroccoli** [bookingcom/shipper#31]
As a followup on #11, @parhamdoustdar suggested to create this ticket as a side note to ourselves.

The problem. Geven: a new application, a vanguard strategy (3 steps: 0, 50%, 100%). A new release is happening and is progressing to step 1 (50% traffic). An abort happens (release object removal). Shipper immediately re-creates a release object and moves it back to step 0. The release itself will skip any waiting-for-traffic steps and go straight to waiting-for-command step. As suggested by @parhamdoustdar, this is somewhat we might handle with a better care.

Expected behavior: release reports at least 1 more intermediate step, like: waiting-for-traffic.

This issue requires a precise definition of an expected behavior of a release object.

**Comment by kanatohodets** [comment]
I think this will be resolved by #24: a more explicit communication between target objects and strategy. This is basically a bug because of the unidirectional comparisons in our traffic strategy checks, which is what #24 attempts to address. The code in question is located [here](https://github.com/bookingcom/shipper/blob/13333ef81b6bc2f398377b863546c4dfa1aba04c/pkg/controller/strategy/comparisons.go#L4).

Given that, I'd like to close this as a dup of #24 if that makes sense to you.

**Comment by icanhazbroccoli** [comment]
@kanatohodets totally makes sense, thanks!

**Comment by parhamdoustdar** [comment]
Yes, agreed.

**Comment by kanatohodets** [comment]
Great, thanks. Closing as dup of #24.
