### ISSUE TITLE
Shipper Doesn't Work With Resyncs Disabled

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#77]
If you run Shipper with resyncs disabled, there are cases where Shipper will get stuck while taking a release forward.

This is because sometimes we rely on the resync to happen, and we don't do as much as we can in each sync loop.

We haven't dug into this yet, so the best way to reproduce this is to run the end-to-end tests while running Shipper with the resync period of 0 to disable all resyncs, and go from there.

**Comment by juliogreff** [comment]
I followed the suggestion of just running the end-to-end tests. Much to my surprise, they all passed. Unfortunately, that seems to be because in current master there's no way to completely disable resyncs. I fixed that in 7ae1c636b93eeb680faea8fedfa69e228dd43ad6.

With those changes, I get one failing test:

```
--- FAIL: TestRolloutAbort (73.78s)
    e2e_test.go:751: waiting for release "my-test-app-77cf3473-0" took 1.597339649s
    e2e_test.go:840: waiting for completion of "my-test-app-77cf3473-0" took 18.399953573s
    e2e_test.go:617: waiting for contender release to appear after editing app "my-test-app"
    e2e_test.go:751: waiting for release "my-test-app-3037a9fd-0" took 1.598389769s
    e2e_test.go:624: setting contender release "my-test-app-3037a9fd-0" targetStep to 0
    e2e_test.go:627: waiting for contender release "my-test-app-3037a9fd-0" to achieve waitingForCommand for targetStep 0
    e2e_test.go:761: release strategy state transition: "" -> "release \"my-test-app-3037a9fd-0\" has no achievedStep reported yet"
    e2e_test.go:761: release strategy state transition: "release \"my-test-app-3037a9fd-0\" has no achievedStep reported yet" -> "{installation: False, capacity: False, traffic: False, command: True}"
    e2e_test.go:819: waiting for command took 10.398270118s
    e2e_test.go:633: checking that incumbent "my-test-app-77cf3473-0" has 4 pods and contender "my-test-app-3037a9fd-0" has 1 pods (strategy step 0 -- 100/1)
    e2e_test.go:624: setting contender release "my-test-app-3037a9fd-0" targetStep to 1
    e2e_test.go:627: waiting for contender release "my-test-app-3037a9fd-0" to achieve waitingForCommand for targetStep 1
    e2e_test.go:761: release strategy state transition: "" -> "{installation: False, capacity: True, traffic: False, command: False}"
    e2e_test.go:761: release strategy state transition: "{installation: False, capacity: True, traffic: False, command: False}" -> "{installation: False, capacity: False, traffic: True, command: False}"
    e2e_test.go:761: release strategy state transition: "{installation: False, capacity: False, traffic: True, command: False}" -> "{installation: False, capacity: False, traffic: False, command: True}"
    e2e_test.go:819: waiting for command took 6.397543921s
    e2e_test.go:633: checking that incumbent "my-test-app-77cf3473-0" has 2 pods and contender "my-test-app-3037a9fd-0" has 2 pods (strategy step 1 -- 50/50)
    e2e_test.go:761: release strategy state transition: "" -> "{installation: False, capacity: False, traffic: False, command: False}"
    e2e_test.go:814: timed out waiting for release to be waiting for capacity: waited 30s. final state: {installation: False, capacity: False, traffic: False, command: False}
FAIL
FAIL    github.com/bookingcom/shipper/test/e2e  104.361s
```

This particular instance happens because the strategy controller doesn't watch for releases being deleted, so the rollout abort gets stuck thinking it still has capacity. A cursory look also shows that most controllers don't handle deleted resources either, so even if this particular broken test gets fixed it doesn't mean we have fixed the entire problem.

**Comment by juliogreff** [comment]
Indeed, fixing that particular test wasn't the end of it. Even though all the tests passed when ran locally, CI had many more issues that were fixed in #88. Now all tests pass with resyncs disabled, but while fixing the breakage I found one major blocker that prevents us from running with resyncs disabled for real: things can fail for long enough so that they're dropped off of the queue, making things "stuck" after a while. I opened #90 so we can take care of that. Until it gets solved, this issue will remain open.

**Comment by juliogreff** [comment]
It turns out that the janitor controller also relies on resyncs: https://github.com/bookingcom/shipper/blob/master/pkg/controller/janitor/controller.go#L306-L331

**Comment by juliogreff** [comment]
Cleaning up an Application's stale releases is also executed without checking for errors and bubbling them up: https://github.com/bookingcom/shipper/blob/master/pkg/controller/application/application_controller.go#L348

**Comment by juliogreff** [comment]
Now that #77 is merged, we can finally close this! \o/
