### ISSUE TITLE
Surface Chart Render Errors

### ISSUE THREAD

**Issue by parhamdoustdar** [bookingcom/shipper#92]
Right now, when there is an error in rendering a chart, we don't surface it anywhere. The Application object says that we are rolling out, ubt it's not true, because no new release gets created for it.

We should have a `ChartIsValid` condition that is set to `false` in this case with the error message we get from Helm.

**Comment by juliogreff** [comment]
I may be holding it wrong, but I don't think that your description is accurate. I created an Application with a broken chart, and a release got created (which means the app is indeed rolling out), with a proper condition, as shown below:

```json
"status": {
    "conditions": [
        {
            "lastTransitionTime": "2019-06-14T09:27:45Z",
            "message": "Chart invalid-chart-template-0.0.1 failed to render: could not render the chart: render error in \"invalid-chart-template/templates/deployment.yaml\": template: invalid-chart-template/templates/deployment.yaml:4:20: executing \"invalid-chart-template/templates/deployment.yaml\" at \u003c{{template \"some-nonsense.fullname\" .}}\u003e: template \"some-nonsense.fullname\" not defined",
            "reason": "BrokenChart",
            "status": "False",
            "type": "Scheduled"
        }
    ]
}
```

Maybe this happens to specific types of brokenness?

**Comment by parhamdoustdar** [comment]
Then my understanding is probably not up to date. We needed the replica count to create the release because the replica count was an annotation on the Release object itself. If that's not true any more, that would explain it.

**Comment by juliogreff** [comment]
A new release is created by the application controller (https://github.com/bookingcom/shipper/blob/master/pkg/controller/application/application_controller.go#L369), and apparently it doesn't do anything at all with charts (https://github.com/bookingcom/shipper/blob/master/pkg/controller/application/application_controller_utils.go#L20-L62). That seems to be the case since c99aa536e8d9d3cff41fbb30fa0bfe36f513c579, which I think will look familiar to you :) 

So as far as I can tell, we're good to close this one!

**Comment by parhamdoustdar** [comment]
Awesome! Thanks for checking this!
