### ISSUE TITLE
Upgrade client-go

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#93]

**Comment by ksurent** [comment]
Relevant: https://github.com/bookingcom/shipper/tree/asurikov/kubernetes-1.11.4.
This is meant as the first step to bring client-go to something more up–to–date. There's an issue though. Modern client-go versions have a completely new dynamic client. There is also a backward compatibility layer in the form of the `deprecated-dynamic` package. The problem is that it does not have a corresponding fake package and that breaks tests.
